
import React from 'react';
import { ClearIcon } from './icons';

interface PrivacyPolicyModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const PrivacyPolicyModal: React.FC<PrivacyPolicyModalProps> = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black bg-opacity-75 backdrop-blur-sm p-4 animate-fade-in">
            <div className="bg-gray-800 border border-gray-700 rounded-xl shadow-2xl max-w-2xl w-full h-3/4 overflow-hidden transform transition-all animate-slide-up">
                <div className="flex justify-between items-center p-4 border-b border-gray-700 bg-gray-900/50">
                    <h2 className="text-xl font-bold text-cyan-400">Privacy Policy</h2>
                    <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
                        <ClearIcon className="w-6 h-6" />
                    </button>
                </div>
                <div className="p-6 space-y-5 text-gray-300 overflow-y-auto h-full pb-20">
                    <p className="text-sm text-gray-500">Last updated: October 26, 2023</p>
                    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    <h3 className="text-lg font-semibold text-cyan-400 mt-4">Interpretation and Definitions</h3>
                    <h4 className="text-md font-semibold text-gray-400 mt-2">Interpretation</h4>
                    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    <h4 className="text-md font-semibold text-gray-400 mt-2">Definitions</h4>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc list-inside space-y-2">
                        <li>
                            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
                        </li>
                        <li>
                            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Target Analyzer.
                        </li>
                        <li>
                            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                        </li>
                        <li>
                            <strong>Country</strong> refers to: Ontario, Canada
                        </li>
                        <li>
                            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                        </li>
                        <li>
                            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
                        </li>
                        <li>
                            <strong>Service</strong> refers to the Website.
                        </li>
                        <li>
                            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
                        </li>
                        <li>
                            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                        </li>
                        <li>
                            <strong>Website</strong> refers to Target Analyzer, accessible from https://target-analyzer.com
                        </li>
                        <li>
                            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                        </li>
                    </ul>
                    <h3 className="text-lg font-semibold text-cyan-400 mt-4">Collecting and Using Your Personal Data</h3>
                    <h4 className="text-md font-semibold text-gray-400 mt-2">Types of Data Collected</h4>
                    <h5 className="text-sm font-semibold text-gray-400 mt-1">Personal Data</h5>
                    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                    <ul className="list-disc list-inside space-y-2">
                        <li>Usage Data</li>
                    </ul>
                    <h5 className="text-sm font-semibold text-gray-400 mt-1">Usage Data</h5>
                    <p>Usage Data is collected automatically when using the Service.</p>
                    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
                    <h4 className="text-md font-semibold text-gray-400 mt-2">Tracking Technologies and Cookies</h4>
                    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                    <ul className="list-disc list-inside space-y-2">
                        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                    </ul>
                </div>
                <div className="p-4 bg-gray-900/50 text-right absolute bottom-0 w-full">
                    <button 
                        onClick={onClose}
                        className="px-5 py-2 bg-gray-700 hover:bg-gray-600 hover:text-white text-gray-200 rounded-lg transition-all font-medium"
                    >
                        Close
                    </button>
                </div>
            </div>
            <style>{`
                @keyframes fade-in {
                    from { opacity: 0; }
                    to { opacity: 1; }
                }
                @keyframes slide-up {
                    from { opacity: 0; transform: translateY(20px); }
                    to { opacity: 1; transform: translateY(0); }
                }
                .animate-fade-in {
                    animation: fade-in 0.2s ease-out forwards;
                }
                .animate-slide-up {
                    animation: slide-up 0.3s ease-out forwards;
                }
            `}</style>
        </div>
    );
};
